---
language: java
dist: xenial

jdk:
- openjdk8

notifications:
  email: false

branches:
  except:
  - gh-pages

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
    - MVN_ARGS="--settings build/.travis.settings.xml"

stages:
  - name: Build-Test

before_install:
  - sudo apt-get update
  - env | grep TRAVIS

jobs:
  include:
    - stage: Build-Test
      jdk: openjdk8
      install: true
      script:
        - build/setMavenVersion.sh
        #- mvn verify -fae -DskipITs $MVN_ARGS
        - mvn nondex:debug
        #- mvn test -fae -DskipITs $MVN_ARGS
      after_success:
        - echo "Build is successful"